#!/usr/bin/env python3
#
#  Task1Week1.py
#  
#  Copyright 2026 Unknown <rasp4@raspberrypi>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

# Pin Definitions
in1, in2, en1 = 17, 18, 27  # Left Motor
in3, in4, en2 = 23, 24, 22  # Right Motor

# Setup pins
pins = [in1, in2, en1, in3, in4, en2]
for pin in pins:
    GPIO.setup(pin, GPIO.OUT)

# Initialize PWM outside the loop
pwm_left = GPIO.PWM(en1, 500)
pwm_right = GPIO.PWM(en2, 500)
pwm_left.start(0)
pwm_right.start(0)

def set_speed(speed):
    pwm_left.ChangeDutyCycle(speed)
    pwm_right.ChangeDutyCycle(speed)

def forwards():
    GPIO.output(in1, True)
    GPIO.output(in2, False)
    GPIO.output(in3, True)
    GPIO.output(in4, False)
    
def backwards():
    GPIO.output(in1, False)
    GPIO.output(in2, True)
    GPIO.output(in3, False)
    GPIO.output(in4, True)

def stop():
    GPIO.output(in1, False)
    GPIO.output(in2, False)
    GPIO.output(in3, False)
    GPIO.output(in4, False)
    set_speed(0)
    
def left():
    GPIO.output(in1,False)
    GPIO.output(in2, True)
    GPIO.output(in3, True)
    GPIO.output(in4, False)
    pwm_left.ChangeDutyCycle(100)
    pwm_right.ChangeDutyCycle(100)
    
def right():
    GPIO.output(in1, True)
    GPIO.output(in2, False)
    GPIO.output(in3, False)
    GPIO.output(in4, True)
    pwm_left.ChangeDutyCycle(100)
    pwm_right.ChangeDutyCycle(100)

try:
    while True:
        cmd = input("Command: ").lower()
        if cmd == "w":
            print("Moving Forward...")
            forwards()
            set_speed(50) 
            time.sleep(2)
            stop()
        
        elif cmd == "a":
            print("Moving left...")
            left()
            time.sleep(2)
            stop()
        
        elif cmd == "d":
            print("Moving right...")
            right()
            time.sleep(2)
            stop()
        
        elif cmd == "s":
            print("Moving backwards...")
            backwards()
            set_speed(50) 
            time.sleep(2)
            stop()
        
        elif cmd == "x":
            print("stop...")
            stop()
            set_speed(0) 
            time.sleep(3)
            stop()
           
        else:
           stop()
           set_speed(0)
           
        
except KeyboardInterrupt:
    # Graceful exit on Ctrl+C
    stop()
    GPIO.cleanup()

    
   
    



